CREATE SCHEMA IF NOT EXISTS ccd410;

-- ======================
-- Pessoa
-- ======================
CREATE TABLE ccd410.pessoa (
  pessoaID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cpf CHAR(11) NOT NULL UNIQUE,
  nome VARCHAR(128) NOT NULL,
  dtNascimento DATE NOT NULL,
  telefone CHAR(14) NOT NULL,
  cep CHAR(9) NOT NULL,
  cidade VARCHAR(128) NOT NULL,
  uf CHAR(2) NOT NULL,
  logradouro VARCHAR(256) NOT NULL,
  numLogradouro VARCHAR(32) NOT NULL,
  complemento VARCHAR(128)
);

-- ======================
-- Funcionario
-- ======================
CREATE TABLE ccd410.funcionario (
  funcionarioID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login VARCHAR(256) NOT NULL,
  senha VARCHAR(256) NOT NULL,
  statusFuncionario VARCHAR(128) NOT NULL,
  dtContratacao DATE NOT NULL,
  pessoaID INT NOT NULL,
  FOREIGN KEY (pessoaID) REFERENCES ccd410.pessoa(pessoaID)
);

-- ======================
-- Paciente
-- ======================
CREATE TABLE ccd410.paciente (
  pacienteID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  planoDeSaude VARCHAR(256) NOT NULL,
  numCarteiraPlano VARCHAR(128) NOT NULL,
  tipoSanguineo CHAR(3) NOT NULL,
  pessoaID INT NOT NULL,
  FOREIGN KEY (pessoaID) REFERENCES ccd410.pessoa(pessoaID)
);

-- ======================
-- Medico
-- ======================
CREATE TABLE ccd410.medico (
  funcionarioID INT PRIMARY KEY,
  especialidade VARCHAR(128) NOT NULL,
  crm CHAR(13) NOT NULL UNIQUE,
  FOREIGN KEY (funcionarioID) REFERENCES ccd410.funcionario(funcionarioID)
);

-- ======================
-- Enfermeiro
-- ======================
CREATE TABLE ccd410.enfermeiro (
  funcionarioID INT PRIMARY KEY,
  coren CHAR(20) NOT NULL UNIQUE,
  FOREIGN KEY (funcionarioID) REFERENCES ccd410.funcionario(funcionarioID)
);

-- ======================
-- Recepcionista
-- ======================
CREATE TABLE ccd410.recepcionista (
  funcionarioID INT PRIMARY KEY,
  setor VARCHAR(128),
  ramal INT NOT NULL,
  telefoneProfissional CHAR(14) NOT NULL UNIQUE,
  FOREIGN KEY (funcionarioID) REFERENCES ccd410.funcionario(funcionarioID)
);

-- ======================
-- Consulta
-- ======================
CREATE TABLE ccd410.consulta (
  consultaID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dtConsulta DATE NOT NULL,
  retorno BOOLEAN NOT NULL,
  descricao VARCHAR(512) NOT NULL,
  encaminhamento VARCHAR(256) NOT NULL,
  pacienteID INT NOT NULL,
  funcionarioID INT NOT NULL,
  FOREIGN KEY (pacienteID) REFERENCES ccd410.paciente(pacienteID),
  FOREIGN KEY (funcionarioID) REFERENCES ccd410.medico(funcionarioID)
);

-- ======================
-- Alergias
-- ======================
CREATE TABLE ccd410.alergias (
  alergiaID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(256) NOT NULL,
  pacienteID INT NOT NULL,
  FOREIGN KEY (pacienteID) REFERENCES ccd410.paciente(pacienteID)
);

-- ======================
-- Remedios Recorrentes
-- ======================
CREATE TABLE ccd410.remedios_recorrentes (
  remediosID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(256) NOT NULL,
  pacienteID INT NOT NULL,
  FOREIGN KEY (pacienteID) REFERENCES ccd410.paciente(pacienteID)
);

-- ======================
-- Exames Solicitados
-- ======================
CREATE TABLE ccd410.exames_solicitados (
  examesID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(256) NOT NULL,
  especialidade VARCHAR(256) NOT NULL,
  descricao VARCHAR(256),
  resultado VARCHAR(512),
  consultaID INT NOT NULL,
  FOREIGN KEY (consultaID) REFERENCES ccd410.consulta(consultaID)
);
